import { User, Section } from "../types/User";

export const SECTIONS = [
  "Newton",
  "Bernoulli",
  "Galileo",
  "Charles",
  "Boyle",
] as const;

export const LEADERBOARD_CATEGORIES = ["SECTION", "BATCH"];

export const NOTIFICATION_CATEGORIES = ["GENERAL", "CLUB"];

export const ACCOUNT_TYPES = ["student", "admin"] as const;

export const dummyUsers: User[] = [
  {
    type: "student",
    username: "juan",
    name: "Juan Dela Cruz",
    email: "juan.delacruz@example.com",
    year: 2025,
    section: "Galileo",
    points: {
      character: 1200,
      participation: 800,
    },
    achievements: [{ title: "Best in Math" }, { title: "Best in Science" }],
    titles: [{ title: "Early Bird" }],
    clubs: [{ name: "Science" }],
    following: [{ username: "maria" }, { username: "pedro" }],
    followers: [{ username: "sofia" }, { username: "elena" }],
  },
  {
    type: "student",
    username: "maria",
    name: "Maria Santos",
    email: "maria.santos@example.com",
    year: 2026,
    section: "Bernoulli",
    points: {
      character: 1500,
      participation: 950,
    },
    achievements: [{ title: "Debate Champion" }],
    titles: [{ title: "Leader" }],
    clubs: [{ name: "Debate" }, { name: "Drama" }],
    following: [{ username: "sofia" }, { username: "juan" }],
    followers: [{ username: "ana" }, { username: "juan" }],
  },
  {
    type: "student",
    username: "pedro",
    name: "Pedro Reyes",
    email: "pedro.reyes@example.com",
    year: 2025,
    section: "Galileo",
    points: {
      character: 900,
      participation: 700,
    },
    achievements: [{ title: "Perfect Attendance" }],
    titles: [{ title: "Consistent" }],
    clubs: [{ name: "Math" }],
    following: [{ username: "juan" }],
    followers: [{ username: "sofia" }],
  },
  {
    type: "student",
    username: "ana",
    name: "Ana Lopez",
    email: "ana.lopez@example.com",
    year: 2027,
    section: "Newton",
    points: {
      character: 1100,
      participation: 600,
    },
    achievements: [{ title: "Essay Contest Winner" }],
    titles: [{ title: "Writer" }],
    clubs: [{ name: "Literature" }],
    following: [{ username: "maria" }],
    followers: [{ username: "isabella" }],
  },
  {
    type: "student",
    username: "carlos",
    name: "Carlos Ramos",
    email: "carlos.ramos@example.com",
    year: 2024,
    section: "Charles",
    points: {
      character: 1000,
      participation: 500,
    },
    achievements: [{ title: "Sports MVP" }],
    titles: [{ title: "Athlete" }],
    clubs: [{ name: "Basketball" }],
    following: [{ username: "diego" }],
    followers: [{ username: "miguel" }],
  },
  {
    type: "student",
    username: "sofia",
    name: "Sofia Mendoza",
    email: "sofia.mendoza@example.com",
    year: 2026,
    section: "Boyle",
    points: {
      character: 1300,
      participation: 850,
    },
    achievements: [{ title: "Science Fair Winner" }],
    titles: [{ title: "Innovator" }],
    clubs: [{ name: "Robotics" }, { name: "Science" }],
    following: [{ username: "juan" }, { username: "maria" }],
    followers: [{ username: "isabella" }],
  },
  {
    type: "student",
    username: "diego",
    name: "Diego Cruz",
    email: "diego.cruz@example.com",
    year: 2025,
    section: "Galileo",
    points: {
      character: 950,
      participation: 780,
    },
    achievements: [{ title: "Coding Champion" }],
    titles: [{ title: "Techie" }],
    clubs: [{ name: "Programming" }],
    following: [{ username: "carlos" }],
    followers: [{ username: "miguel" }],
  },
  {
    type: "student",
    username: "isabella",
    name: "Isabella Torres",
    email: "isabella.torres@example.com",
    year: 2027,
    section: "Newton",
    points: {
      character: 1400,
      participation: 1000,
    },
    achievements: [{ title: "Art Contest Winner" }],
    titles: [{ title: "Creative" }],
    clubs: [{ name: "Art" }, { name: "Drama" }],
    following: [{ username: "ana" }, { username: "sofia" }],
    followers: [{ username: "elena" }],
  },
  {
    type: "student",
    username: "miguel",
    name: "Miguel Flores",
    email: "miguel.flores@example.com",
    year: 2024,
    section: "Charles",
    points: {
      character: 800,
      participation: 650,
    },
    achievements: [{ title: "Music Festival Winner" }],
    titles: [{ title: "Performer" }],
    clubs: [{ name: "Music" }],
    following: [{ username: "carlos" }],
    followers: [{ username: "diego" }],
  },
  {
    type: "student",
    username: "elena",
    name: "Elena Garcia",
    email: "elena.garcia@example.com",
    year: 2025,
    section: "Newton",
    points: {
      character: 1250,
      participation: 900,
    },
    achievements: [{ title: "Community Volunteer" }],
    titles: [{ title: "Helper" }],
    clubs: [{ name: "Community Service" }],
    following: [{ username: "isabella" }],
    followers: [{ username: "juan" }],
  },
];
